const dataEstablecimientos = [
    { idComuna: 'idConcepcion' , idTipo: 'idUnidadSaludFuncionarios' , nombre: 'Unidad de Salud Funcionario S.S Concepción' },
    { idComuna: 'idTalcahuano' , idTipo: 'idUnidadSaludFuncionarios' , nombre: 'Unidad de Salud Funcionario  S.S Talcahuano' },
    { idComuna: 'idConcepcion' , idTipo: 'idVacunatorio' , nombre: 'Centro de Vacunación y Servcio de Enfermería SpA' },
    { idComuna: 'idConcepcion' , idTipo: 'idCentroSalud' , nombre: 'Centro Médico Medisan' },
    { idComuna: 'idLosAngeles' , idTipo: 'idSAR' , nombre: 'SAR Entre Ríos' },
    { idComuna: 'idConcepcion' , idTipo: 'idClinicaDental' , nombre: 'Centro Odontológico Uno Salud Dental Concepción' },
    { idComuna: 'idConcepcion' , idTipo: 'idClinicaDental' , nombre: 'Centro Odontológico Uno Salud Dental Concepción Dos' },
    { idComuna: 'idTalcahuano' , idTipo: 'idClinicaDental' , nombre: 'Centro Odontológico Uno Salud Dental Talcahuano' },
    { idComuna: 'idLosAngeles' , idTipo: 'idClinicaDental' , nombre: 'Centro Odontológico Uno Salud Dental Los Ángeles' },
    { idComuna: 'idConcepcion' , idTipo: 'idVacunatorio' , nombre: 'Vacunatorio Seres' },
    { idComuna: 'idConcepcion' , idTipo: 'idVacunatorio' , nombre: 'Vacunatorio Biovax SpA' },
    { idComuna: 'idChiguayante' , idTipo: 'idSAR' , nombre: 'SAR Chiguayante' },
    { idComuna: 'idSanPedroDeLaPaz' , idTipo: 'idSAR' , nombre: 'SAR San Pedro' },
    { idComuna: 'idSanPedroDeLaPaz' , idTipo: 'idClinicaDental' , nombre: 'Centro Odontológico Uno Salud Dental San Pedro de la Paz' },
    { idComuna: 'idTalcahuano' , idTipo: 'idCOSAM' , nombre: 'COSAM Los Cerros' },
    { idComuna: 'idCoronel' , idTipo: 'idVacunatorio' , nombre: 'Centro Vacunatorio Coronel' },
    { idComuna: 'idConcepcion' , idTipo: 'idVacunatorio' , nombre: 'Vacunatorio Concepción' },
    { idComuna: 'idConcepcion' , idTipo: 'idVacunatorio' , nombre: 'Vacunatorio Centro de Diagnóstico San Martín' },
    { idComuna: 'idSanPedroDeLaPaz' , idTipo: 'idVacunatorio' , nombre: 'Vacunatorio San Pedro SpA' },
    { idComuna: 'idConcepcion' , idTipo: 'idSML' , nombre: 'Servicio Médico Legal Concepción' },
    { idComuna: 'idLosAngeles' , idTipo: 'idSML' , nombre: 'Servicio Médico Legal Los Ángeles' },
    { idComuna: 'idTalcahuano' , idTipo: 'idDispositivoCrisisSanitaria' , nombre: 'Buque Talcahuano' },
    { idComuna: 'idConcepcion' , idTipo: 'idDispositivoCrisisSanitaria' , nombre: 'Dispositivo Modular de Salud Hospital Guillermo Grant Benavente' },
    { idComuna: 'idTirua' , idTipo: 'idSUR' , nombre: 'SUR Isabel Jiménez' },
    { idComuna: 'idArauco' , idTipo: 'idSUR' , nombre: 'SUR Laraquete' },
    { idComuna: 'idLosAngeles' , idTipo: 'idCentroDialisis' , nombre: 'Centro de Dialisis Los Angeles ' },
    { idComuna: 'idLosAngeles' , idTipo: 'idCentroDialisis' , nombre: 'Diálisis Nueva Vida S.p.A.' },
    { idComuna: 'idConcepcion' , idTipo: 'idCentroDialisis' , nombre: 'Servicios Médicos Medinefro Ltda.' },
    { idComuna: 'idMulchen' , idTipo: 'idCentroDialisis' , nombre: 'Centro de Diálisis Los Ángeles Sucursal Mulchén' },
    { idComuna: 'idArauco' , idTipo: 'idCentroDialisis' , nombre: 'Centro de Diálisis y Especialidades Médicas Arauco Ltda.' },
    { idComuna: 'idConcepcion' , idTipo: 'idCentroDialisis' , nombre: 'Clínica de Diálisis Diasermed' },
    { idComuna: 'idConcepcion' , idTipo: 'idCentroDialisis' , nombre: 'Servicios Médicos CIDIAL Ltda.' },
    { idComuna: 'idArauco' , idTipo: 'idSUR' , nombre: 'SUR Carampangue' },
    { idComuna: 'idArauco' , idTipo: 'idSUR' , nombre: 'SUR Tubul' },
    { idComuna: 'idHualpen' , idTipo: 'idSAPU' , nombre: 'SAPU Dental Hualpén' },
    { idComuna: 'idCoronel' , idTipo: 'idCentroSalud' , nombre: 'Clínica de Atención Ambulatoria Mutual de Seguridad Coronel' },
    { idComuna: 'idSanPedroDeLaPaz' , idTipo: 'idSAR' , nombre: 'SAR Boca Sur' },
    { idComuna: 'idTome' , idTipo: 'idSUR' , nombre: 'SUR Dichato' },
    { idComuna: 'idLosAngeles' , idTipo: 'idSUR' , nombre: 'SUR Santa Fe' },
    { idComuna: 'idAntuco' , idTipo: 'idSUR' , nombre: 'SUR Antuco' },
    { idComuna: 'idCabrero' , idTipo: 'idSUR' , nombre: 'SUR Monteaguila' },
    { idComuna: 'idQuilleco' , idTipo: 'idSUR' , nombre: 'SUR Quilleco' },
    { idComuna: 'idNegrete' , idTipo: 'idSUR' , nombre: 'SUR Negrete' },
    { idComuna: 'idSanRosendo' , idTipo: 'idSUR' , nombre: 'SUR San Rosendo' },
    { idComuna: 'idAltoBioBio' , idTipo: 'idSUR' , nombre: 'SUR Ralco' },
    { idComuna: 'idYumbel' , idTipo: 'idSUR' , nombre: 'SUR Yumbel Estación' },
    { idComuna: 'idQuilleco' , idTipo: 'idSUR' , nombre: 'SUR Canteras Villa Mercedes' },
    { idComuna: 'idQuilaco' , idTipo: 'idSUR' , nombre: 'SUR Quilaco' },
    { idComuna: 'idTalcahuano' , idTipo: 'idSAR' , nombre: 'SAR Los Cerros' },
    { idComuna: 'idLosAngeles' , idTipo: 'idUnidadSaludFuncionarios' , nombre: 'Unidad de Salud Funcionario S.S Bíobío' },
    { idComuna: 'idLebu' , idTipo: 'idUnidadSaludFuncionarios' , nombre: 'Unidad de Salud Funcionario  S.S Arauco' },
    { idComuna: 'idConcepcion' , idTipo: 'idDireccionServicioSalud' , nombre: 'Actividades gestionadas por la Dirección del Servicio para apoyo de la Red (S.S de Concepción)' },
    { idComuna: 'idConcepcion' , idTipo: 'idPRAIS' , nombre: 'PRAIS (S.S Concepción)' },
    { idComuna: 'idConcepcion' , idTipo: 'idHospital' , nombre: 'Hospital Clínico Regional Dr. Guillermo Grant Benavente (Concepción)' },
    { idComuna: 'idConcepcion' , idTipo: 'idHospital' , nombre: 'Hospital Traumatológico (Concepción)' },
    { idComuna: 'idCoronel' , idTipo: 'idHospital' , nombre: 'Hospital San José (Coronel)' },
    { idComuna: 'idLota' , idTipo: 'idHospital' , nombre: 'Hospital de Lota' },
    { idComuna: 'idSantaJuana' , idTipo: 'idHospital' , nombre: 'Hospital Clorinda Avello (Santa Juana)' },
    { idComuna: 'idFlorida' , idTipo: 'idHospital' , nombre: 'Hospital San Agustín de Florida' },
    { idComuna: 'idConcepcion' , idTipo: 'idCDT' , nombre: 'Centro de Especialidades de Medicina Transfusional' },
    { idComuna: 'idConcepcion' , idTipo: 'idHospital' , nombre: 'Hospital Clínico del Sur S.A.' },
    { idComuna: 'idConcepcion' , idTipo: 'idClinica' , nombre: 'Clínica de la Mujer Sanatorio Alemán' },
    { idComuna: 'idConcepcion' , idTipo: 'idCentroSalud' , nombre: 'Centro Clínico Militar Concepción' },
    { idComuna: 'idConcepcion' , idTipo: 'idClinica' , nombre: 'Servicios Clínicos Neuropsiquiátricos y Geriátricos R y G Limitada' },
    { idComuna: 'idConcepcion' , idTipo: 'idCentroSalud' , nombre: 'Centro Penitenciario' },
    { idComuna: 'idConcepcion' , idTipo: 'idLabClinicoDental' , nombre: 'Laboratorio Clínico Bionet S.A. - Concepción' },
    { idComuna: 'idConcepcion' , idTipo: 'idCentroSalud' , nombre: 'Policlínico Agencia Concepción de la Asociación Chilena de Seguridad' },
    { idComuna: 'idTalcahuano' , idTipo: 'idCentroSalud' , nombre: 'Centro Integramédica del Trébol' },
    { idComuna: 'idConcepcion' , idTipo: 'idCentroMedicoDental' , nombre: 'Megasalud S.A. Centro Médico y Dental Concepción' },
    { idComuna: 'idHualpen' , idTipo: 'idVacunatorio' , nombre: 'Vacunatorio Clínica Universitaria de Concepción' },
    { idComuna: 'idConcepcion' , idTipo: 'idCentroSalud' , nombre: 'Centro Médico Inmunomédica' },
    { idComuna: 'idConcepcion' , idTipo: 'idCentroMedicoDental' , nombre: 'Centro y Médico Dental VIII Zona de Carabineros (Del Bíobío)' },
    { idComuna: 'idConcepcion' , idTipo: 'idVacunatorio' , nombre: 'Vacunatorio El Salvador' },
    { idComuna: 'idConcepcion' , idTipo: 'idVacunatorio' , nombre: 'Kiñewen Ltda.' },
    { idComuna: 'idSanPedroDeLaPaz' , idTipo: 'idVacunatorio' , nombre: 'Vacunatorio Endodent' },
    { idComuna: 'idConcepcion' , idTipo: 'idCentroSalud' , nombre: 'Departamento de Salud Estudiantil Universidad del Bíobío Campus Concepción' },
    { idComuna: 'idConcepcion' , idTipo: 'idVacunatorio' , nombre: 'Vacunatorio Israel' },
    { idComuna: 'idChiguayante' , idTipo: 'idCESFAM' , nombre: 'Centro de Salud Familiar Pinares' },
    { idComuna: 'idSanPedroDeLaPaz' , idTipo: 'idCESFAM' , nombre: 'Centro de Salud Familiar Boca Sur' },
    { idComuna: 'idConcepcion' , idTipo: 'idCESFAM' , nombre: 'Centro de Salud Familiar Pedro de Valdivia' },
    { idComuna: 'idConcepcion' , idTipo: 'idCESFAM' , nombre: 'Centro de Salud Familiar OHiggins' },
    { idComuna: 'idConcepcion' , idTipo: 'idCESFAM' , nombre: 'Centro de Salud Familiar Víctor Manuel Fernández' },
    { idComuna: 'idConcepcion' , idTipo: 'idCESFAM' , nombre: 'Centro de Salud Familiar Tucapel' },
    { idComuna: 'idChiguayante' , idTipo: 'idCESFAM' , nombre: 'Centro de Salud Familiar Chiguayante' },
    { idComuna: 'idSanPedroDeLaPaz' , idTipo: 'idCESFAM' , nombre: 'Centro de Salud Familiar San Pedro de La Paz Candelaria' },
    { idComuna: 'idConcepcion' , idTipo: 'idCESFAM' , nombre: 'Centro de Salud Familiar Lorenzo Arenas' },
    { idComuna: 'idConcepcion' , idTipo: 'idCESFAM' , nombre: 'Centro de Salud Familiar Juan Soto Fernández' },
    { idComuna: 'idCoronel' , idTipo: 'idCESFAM' , nombre: 'Centro de Salud Familiar Carlos Pinto Fierro' },
    { idComuna: 'idCoronel' , idTipo: 'idCESFAM' , nombre: 'Centro de Salud Familiar Lagunillas' },
    { idComuna: 'idCoronel' , idTipo: 'idCESFAM' , nombre: 'Centro de Salud Familiar Yobilo' },
    { idComuna: 'idChiguayante' , idTipo: 'idCESFAM' , nombre: 'Centro de Salud Familiar La Leonera' },
    { idComuna: 'idLota' , idTipo: 'idCESFAM' , nombre: 'Centro de Salud Familiar Dr. Sergio Lagos Olave (ex Nº 4 Lota Bajo)' },
    { idComuna: 'idConcepcion' , idTipo: 'idCESFAM' , nombre: 'Centro de Salud Familiar Santa Sabina' },
    { idComuna: 'idSanPedroDeLaPaz' , idTipo: 'idCESFAM' , nombre: 'Centro de Salud Familiar Lomas Coloradas' },
    { idComuna: 'idSanPedroDeLaPaz' , idTipo: 'idCESFAM' , nombre: 'Centro de Salud Familiar San Pedro de La Costa' },
    { idComuna: 'idLota' , idTipo: 'idCESFAM' , nombre: 'Centro de Salud Familiar Dr. Juan Cartes Arias' },
    { idComuna: 'idHualqui' , idTipo: 'idCESFAM' , nombre: 'Centro de Salud Familiar Hualqui' },
    { idComuna: 'idFlorida' , idTipo: 'idPSR' , nombre: 'Posta de Salud Rural Manco' },
    { idComuna: 'idCoronel' , idTipo: 'idPSR' , nombre: 'Posta de Salud Rural Puerto Norte Isla Sta. María' },
    { idComuna: 'idHualqui' , idTipo: 'idPSR' , nombre: 'Posta de Salud Rural Talcamávida' },
    { idComuna: 'idHualqui' , idTipo: 'idPSR' , nombre: 'Posta de Salud Rural Quilacoya' },
    { idComuna: 'idSantaJuana' , idTipo: 'idPSR' , nombre: 'Posta de Salud Rural La Generala' },
    { idComuna: 'idSantaJuana' , idTipo: 'idPSR' , nombre: 'Posta de Salud Rural Colico Alto' },
    { idComuna: 'idSantaJuana' , idTipo: 'idPSR' , nombre: 'Posta de Salud Rural Tanahuillín' },
    { idComuna: 'idSantaJuana' , idTipo: 'idPSR' , nombre: 'Posta de Salud Rural Chacay (Santa Juana)' },
    { idComuna: 'idSantaJuana' , idTipo: 'idPSR' , nombre: 'Posta de Salud Rural Torre Dorada' },
    { idComuna: 'idSantaJuana' , idTipo: 'idPSR' , nombre: 'Posta de Salud Rural Purgatorio' },
    { idComuna: 'idFlorida' , idTipo: 'idPSR' , nombre: 'Posta de Salud Rural Granerillos' },
    { idComuna: 'idFlorida' , idTipo: 'idPSR' , nombre: 'Posta de Salud Rural Cancha Los Monteros' },
    { idComuna: 'idFlorida' , idTipo: 'idPSR' , nombre: 'Posta de Salud Rural Roa' },
    { idComuna: 'idCoronel' , idTipo: 'idPSR' , nombre: 'Posta de Salud Rural Patagual' },
    { idComuna: 'idConcepcion' , idTipo: 'idLabClinicoDental' , nombre: 'Laboratorio Clínico Hasiles' },
    { idComuna: 'idConcepcion' , idTipo: 'idLabClinicoDental' , nombre: 'Laboratorio Clínico Seres Ltda.' },
    { idComuna: 'idConcepcion' , idTipo: 'idLabClinicoDental' , nombre: 'Laboratorio Clínico Lincoyán' },
    { idComuna: 'idConcepcion' , idTipo: 'idLabClinicoDental' , nombre: 'Laboratorio Clínico Dr. Raúl Campos y Cía. Ltda.' },
    { idComuna: 'idConcepcion' , idTipo: 'idLabClinicoDental' , nombre: 'Laboratorio Clínico Dr. Gustavo Torrejón Sanhueza y Cía. Ltda.' },
    { idComuna: 'idConcepcion' , idTipo: 'idLabClinicoDental' , nombre: 'Laboratorio Clínico Tecnimed Ltda.' },
    { idComuna: 'idConcepcion' , idTipo: 'idLabClinicoDental' , nombre: 'Laboratorio Clínico Dimet Ltda.' },
    { idComuna: 'idConcepcion' , idTipo: 'idLabClinicoDental' , nombre: 'Laboratorio Clínico Diagonal' },
    { idComuna: 'idConcepcion' , idTipo: 'idLabClinicoDental' , nombre: 'Laboratorio Clínico Castellón' },
    { idComuna: 'idConcepcion' , idTipo: 'idLabClinicoDental' , nombre: 'Laboratorio Clínico Inmunomedica Ltda.' },
    { idComuna: 'idConcepcion' , idTipo: 'idLabClinicoDental' , nombre: 'Laboratorio Clínico C.D.S' },
    { idComuna: 'idConcepcion' , idTipo: 'idLabClinicoDental' , nombre: 'Laboratorio Clínico Schwerter' },
    { idComuna: 'idChiguayante' , idTipo: 'idLabClinicoDental' , nombre: 'Laboratorio Clínico Labotem' },
    { idComuna: 'idConcepcion' , idTipo: 'idLabClinicoDental' , nombre: 'Laboratorio Clínico Diagnomed' },
    { idComuna: 'idConcepcion' , idTipo: 'idLabClinicoDental' , nombre: 'Laboratorio Clínico de Exploración Renal' },
    { idComuna: 'idSanPedroDeLaPaz' , idTipo: 'idCentroSalud' , nombre: 'Instituto Teletón Concepción' },
    { idComuna: 'idCoronel' , idTipo: 'idCentroSalud' , nombre: 'Policlínico de la Asociación Chilena de Seguridad Coronel' },
    { idComuna: 'idConcepcion' , idTipo: 'idHospital' , nombre: 'Hospital de Centro de Cumplimiento Penitenciario Biobío' },
    { idComuna: 'idConcepcion' , idTipo: 'idLabClinicoDental' , nombre: 'Laboratorio Clínico Dr. Fructuoso Biel y Cia Ltda.' },
    { idComuna: 'idConcepcion' , idTipo: 'idLabClinicoDental' , nombre: 'Laboratorio Clínico IMEDIM' },
    { idComuna: 'idConcepcion' , idTipo: 'idCentroSalud' , nombre: 'Centro Médico Radiológico Concepción Ltda.' },
    { idComuna: 'idConcepcion' , idTipo: 'idLabClinicoDental' , nombre: 'Laboratorio de Especialidades Medicas EMSA S.A' },
    { idComuna: 'idCoronel' , idTipo: 'idCOSAM' , nombre: 'COSAM de Coronel' },
    { idComuna: 'idLota' , idTipo: 'idCOSAM' , nombre: 'COSAM Comunitaria Lota' },
    { idComuna: 'idConcepcion' , idTipo: 'idCESFAM' , nombre: 'Centro de Salud Familiar Villa Nonguén (Organizaciones sin fines de lucro y ONG)' },
    { idComuna: 'idFlorida' , idTipo: 'idCECOSF' , nombre: 'Centro Comunitario de Salud Familiar Copiulemu' },
    { idComuna: 'idCoronel' , idTipo: 'idCECOSF' , nombre: 'Centro Comunitario de Salud Familiar Puerto Sur Isla Sta. María' },
    { idComuna: 'idLota' , idTipo: 'idCECOSF' , nombre: 'Centro Comunitario de Salud Familiar Colcura' },
    { idComuna: 'idSanPedroDeLaPaz' , idTipo: 'idCECOSF' , nombre: 'Centro Comunitario de Salud Familiar Boca Sur' },
    { idComuna: 'idCoronel' , idTipo: 'idCECOSF' , nombre: 'Centro Comunitario de Salud Familiar Lagunillas' },
    { idComuna: 'idCoronel' , idTipo: 'idCECOSF' , nombre: 'Centro Comunitario de Salud Familiar Escuadrón' },
    { idComuna: 'idHualqui' , idTipo: 'idCECOSF' , nombre: 'Centro Comunitario de Salud Familiar Hualqui' },
    { idComuna: 'idConcepcion' , idTipo: 'idSAR' , nombre: 'SAR Tucapel' },
    { idComuna: 'idChiguayante' , idTipo: 'idSAPU' , nombre: 'SAPU Dental Chiguayante' },
    { idComuna: 'idSanPedroDeLaPaz' , idTipo: 'idSAPU' , nombre: 'SAPU Dental San Pedro de La Paz' },
    { idComuna: 'idConcepcion' , idTipo: 'idSAPU' , nombre: 'SAPU Lorenzo Arenas' },
    { idComuna: 'idConcepcion' , idTipo: 'idSAPU' , nombre: 'SAPU Juan Soto Fernández' },
    { idComuna: 'idCoronel' , idTipo: 'idSAPU' , nombre: 'SAPU Lagunillas' },
    { idComuna: 'idCoronel' , idTipo: 'idSAPU' , nombre: 'SAPU Yobilo' },
    { idComuna: 'idChiguayante' , idTipo: 'idSAPU' , nombre: 'SAPU Leonera' },
    { idComuna: 'idConcepcion' , idTipo: 'idSAPU' , nombre: 'SAPU Santa Sabina' },
    { idComuna: 'idSanPedroDeLaPaz' , idTipo: 'idSAPU' , nombre: 'SAPU Loma Colorada' },
    { idComuna: 'idHualqui' , idTipo: 'idSAPU' , nombre: 'SAPU Hualqui' },
    { idComuna: 'idTalcahuano' , idTipo: 'idDireccionServicioSalud' , nombre: 'Actividades gestionadas por la Dirección del Servicio para apoyo de la Red (S.S de Talcahuano)' },
    { idComuna: 'idTalcahuano' , idTipo: 'idPRAIS' , nombre: 'PRAIS (S.S Talcahuano)' },
    { idComuna: 'idTalcahuano' , idTipo: 'idHospital' , nombre: 'Hospital Las Higueras (Talcahuano)' },
    { idComuna: 'idTome' , idTipo: 'idHospital' , nombre: 'Hospital de Tomé' },
    { idComuna: 'idPenco' , idTipo: 'idHospital' , nombre: 'Hospital Penco Lirquén' },
    { idComuna: 'idTalcahuano' , idTipo: 'idHospital' , nombre: 'Hospital Instituto de Seguridad del Trabajo Talcahuano' },
    { idComuna: 'idTalcahuano' , idTipo: 'idHospital' , nombre: 'Hospital Naval Almirante Adriazola' },
    { idComuna: 'idTalcahuano' , idTipo: 'idClinica' , nombre: 'Clínica Bio Bio' },
    { idComuna: 'idHualpen' , idTipo: 'idClinica' , nombre: 'Clínica Andes Salud Concepción' },
    { idComuna: 'idHualpen' , idTipo: 'idCentroSalud' , nombre: 'Clínica de Atención Ambulatoria Mutual de Seguridad CChC Hualpén' },
    { idComuna: 'idTalcahuano' , idTipo: 'idLabClinicoDental' , nombre: 'Laboratorio Clínico YUEN' },
    { idComuna: 'idPenco' , idTipo: 'idLabClinicoDental' , nombre: 'Laboratorio Clínico ITAMED' },
    { idComuna: 'idTalcahuano' , idTipo: 'idCentroSalud' , nombre: 'Policlínico de la Asociación Chilena de Seguridad Talcahuano' },
    { idComuna: 'idHualpen' , idTipo: 'idCESFAM' , nombre: 'Centro de Salud Familiar Hualpencillo' },
    { idComuna: 'idTalcahuano' , idTipo: 'idCESFAM' , nombre: 'Centro de Salud Familiar San Vicente' },
    { idComuna: 'idTalcahuano' , idTipo: 'idCESFAM' , nombre: 'Centro de Salud Familiar Alcalde Leocán Portus' },
    { idComuna: 'idPenco' , idTipo: 'idCESFAM' , nombre: 'Centro de Salud Familiar Penco' },
    { idComuna: 'idTome' , idTipo: 'idCESFAM' , nombre: 'Centro de Salud Familiar Dr. Alberto Reyes' },
    { idComuna: 'idTome' , idTipo: 'idCESFAM' , nombre: 'Centro de Salud Familiar Bellavista' },
    { idComuna: 'idTalcahuano' , idTipo: 'idCESFAM' , nombre: 'Centro de Salud Familiar Paulina Avendaño Pereda' },
    { idComuna: 'idTalcahuano' , idTipo: 'idCESFAM' , nombre: 'Centro de Salud Familiar Los Cerros' },
    { idComuna: 'idHualpen' , idTipo: 'idCESFAM' , nombre: 'Centro de Salud Familiar Talcahuano Sur' },
    { idComuna: 'idHualpen' , idTipo: 'idCESFAM' , nombre: 'Centro de Salud Familiar La Floresta' },
    { idComuna: 'idPenco' , idTipo: 'idCESFAM' , nombre: 'Centro de Salud Familiar Lirquén' },
    { idComuna: 'idTalcahuano' , idTipo: 'idPSR' , nombre: 'Posta de Salud Rural Tumbes' },
    { idComuna: 'idTome' , idTipo: 'idPSR' , nombre: 'Posta de Salud Rural Rafael' },
    { idComuna: 'idTome' , idTipo: 'idCESFAM' , nombre: 'Centro de Salud Familiar Dichato' },
    { idComuna: 'idTome' , idTipo: 'idPSR' , nombre: 'Posta de Salud Rural Menque' },
    { idComuna: 'idTome' , idTipo: 'idPSR' , nombre: 'Posta de Salud Rural Coliumo' },
    { idComuna: 'idHualpen' , idTipo: 'idCOSAM' , nombre: 'COSAM Hualpén' },
    { idComuna: 'idHualpen' , idTipo: 'idCECOSF' , nombre: 'Centro Comunitario de Salud Familiar España' },
    { idComuna: 'idTalcahuano' , idTipo: 'idCECOSF' , nombre: 'Centro Comunitario de Salud Familiar 8 de Mayo' },
    { idComuna: 'idPenco' , idTipo: 'idCECOSF' , nombre: 'Centro Comunitario de Salud Familiar Cosmito' },
    { idComuna: 'idPenco' , idTipo: 'idCECOSF' , nombre: 'Centro Comunitario de Salud Familiar Los Forjadores' },
    { idComuna: 'idTalcahuano' , idTipo: 'idCECOSF' , nombre: 'Centro Comunitario de Salud Familiar Esmeralda' },
    { idComuna: 'idHualpen' , idTipo: 'idCECOSF' , nombre: 'Centro Comunitario de Salud Familiar Rene Schneider' },
    { idComuna: 'idHualpen' , idTipo: 'idCECOSF' , nombre: 'Centro Comunitario de Salud Familiar Llafkelen' },
    { idComuna: 'idTome' , idTipo: 'idCECOSF' , nombre: 'Centro Comunitario de Salud Familiar El Santo Esfuerzo de Todos' },
    { idComuna: 'idHualpen' , idTipo: 'idCECOSF' , nombre: 'Centro Comunitario de Salud Familiar Leocán Portus Govinden' },
    { idComuna: 'idTalcahuano' , idTipo: 'idCECOSF' , nombre: 'Centro Comunitario de Salud Familiar Libertad Gaete' },
    { idComuna: 'idTalcahuano' , idTipo: 'idCECOSF' , nombre: 'Centro Comunitario de Salud Familiar Los Lobos la Gloria' },
    { idComuna: 'idHualpen' , idTipo: 'idSAR' , nombre: 'SAR Hualpencillo' },
    { idComuna: 'idTalcahuano' , idTipo: 'idSAR' , nombre: 'SAR San Vicente' },
    { idComuna: 'idTalcahuano' , idTipo: 'idSAPU' , nombre: 'SAPU Paulina Avendaño Pereda' },
    { idComuna: 'idPenco' , idTipo: 'idSAR' , nombre: 'SAR Penco' },
    { idComuna: 'idTome' , idTipo: 'idSAR' , nombre: 'SAR Dr. Alberto Reyes' },
    { idComuna: 'idTalcahuano' , idTipo: 'idSAPU' , nombre: 'SAPU Alcalde Leocán Portus' },
    { idComuna: 'idTalcahuano' , idTipo: 'idSAPU' , nombre: 'SAPU Los Cerros' },
    { idComuna: 'idHualpen' , idTipo: 'idSAPU' , nombre: 'SAPU Talcahuano Sur' },
    { idComuna: 'idLosAngeles' , idTipo: 'idDireccionServicioSalud' , nombre: 'Actividades gestionadas por la Dirección del Servicio para apoyo de la Red (S.S de Bíobío)' },
    { idComuna: 'idLosAngeles' , idTipo: 'idPRAIS' , nombre: 'PRAIS (S.S Bíobío)' },
    { idComuna: 'idTucapel' , idTipo: 'idClinicaDentalMovil' , nombre: 'Clínica Dental Móvil Triple. Pat. UW9511 (Huepil)' },
    { idComuna: 'idSantaBarbara' , idTipo: 'idClinicaDentalMovil' , nombre: 'Clínica Dental Móvil Triple. Pat. NW6995 (Santa Bárbara)' },
    { idComuna: 'idYumbel' , idTipo: 'idClinicaDentalMovil' , nombre: 'Clínica Dental Móvil Triple. Pat. NW6996 (Yumbel)' },
    { idComuna: 'idLosAngeles' , idTipo: 'idHospital' , nombre: 'Complejo Asistencial Dr. Víctor Ríos Ruiz (Los Ángeles)' },
    { idComuna: 'idMulchen' , idTipo: 'idHospital' , nombre: 'Hospital de Mulchén' },
    { idComuna: 'idNacimiento' , idTipo: 'idHospital' , nombre: 'Hospital Comunitario y Familiar de Nacimiento' },
    { idComuna: 'idYumbel' , idTipo: 'idHospital' , nombre: 'Hospital Comunitario de Yumbel' },
    { idComuna: 'idLaja' , idTipo: 'idHospital' , nombre: 'Hospital Comunitario de Laja' },
    { idComuna: 'idSantaBarbara' , idTipo: 'idHospital' , nombre: 'Hospital Comunitario de Santa Bárbara' },
    { idComuna: 'idTucapel' , idTipo: 'idHospital' , nombre: 'Hospital Comunitario Dr. Roberto Muñoz Urrutia de Huépil' },
    { idComuna: 'idLosAngeles' , idTipo: 'idCentroSalud' , nombre: 'Policlínico AChS Los ángeles' },
    { idComuna: 'idLosAngeles' , idTipo: 'idClinica' , nombre: 'Clínica Adventista' },
    { idComuna: 'idNacimiento' , idTipo: 'idCentroSalud' , nombre: 'Policlínico AChS Subregional Nacimiento' },
    { idComuna: 'idLosAngeles' , idTipo: 'idClinica' , nombre: 'Clínica Los Andes' },
    { idComuna: 'idLosAngeles' , idTipo: 'idHospital' , nombre: 'Hospital Mutual de Seguridad CChC Los Ángeles' },
    { idComuna: 'idLosAngeles' , idTipo: 'idCentroMedicoDental' , nombre: 'Megasalud S.A. Centro Médico y Dental Los Ángeles' },
    { idComuna: 'idLosAngeles' , idTipo: 'idLabClinicoDental' , nombre: 'Laboratorio Clínico Central Kojchen y Compañía Limitada' },
    { idComuna: 'idLosAngeles' , idTipo: 'idLabClinicoDental' , nombre: 'Laboratorio Clínico Cordillera' },
    { idComuna: 'idCabrero' , idTipo: 'idLabClinicoDental' , nombre: 'Laboratorio Clínico Biomec' },
    { idComuna: 'idLosAngeles' , idTipo: 'idVacunatorio' , nombre: 'Vacunatorio Buena Salud' },
    { idComuna: 'idLosAngeles' , idTipo: 'idCESFAM' , nombre: 'Centro de Salud Familiar Nororiente de Los Ángeles' },
    { idComuna: 'idLosAngeles' , idTipo: 'idCESFAM' , nombre: 'Centro de Salud Familiar Santa Fe' },
    { idComuna: 'idAntuco' , idTipo: 'idCESFAM' , nombre: 'Centro de Salud Familiar Antuco' },
    { idComuna: 'idCabrero' , idTipo: 'idCESFAM' , nombre: 'Centro de Salud Familiar Monteaguila' },
    { idComuna: 'idCabrero' , idTipo: 'idCESFAM' , nombre: 'Centro de Salud Familiar Lautaro Cáceres Ramos' },
    { idComuna: 'idQuilleco' , idTipo: 'idCESFAM' , nombre: 'Centro de Salud Familiar Quilleco' },
    { idComuna: 'idNegrete' , idTipo: 'idCESFAM' , nombre: 'Centro de Salud Familiar Yanequén' },
    { idComuna: 'idSanRosendo' , idTipo: 'idCESFAM' , nombre: 'Centro de Salud Familiar Dr. Carlos Echeverría Véjar' },
    { idComuna: 'idLosAngeles' , idTipo: 'idCESFAM' , nombre: 'Centro de Salud Familiar 2 Septiembre' },
    { idComuna: 'idLosAngeles' , idTipo: 'idCESFAM' , nombre: 'Centro de Salud Familiar Norte de Los Ángeles' },
    { idComuna: 'idLosAngeles' , idTipo: 'idCESFAM' , nombre: 'Centro de Salud Familiar Paillihue' },
    { idComuna: 'idAltoBioBio' , idTipo: 'idCESFAM' , nombre: 'Centro de Salud Familiar Ralco' },
    { idComuna: 'idYumbel' , idTipo: 'idCESFAM' , nombre: 'Centro de Salud Familiar Yumbel Estación' },
    { idComuna: 'idQuilleco' , idTipo: 'idCESFAM' , nombre: 'Centro de Salud Familiar Canteras Villa Mercedes' },
    { idComuna: 'idLosAngeles' , idTipo: 'idCESFAM' , nombre: 'Centro de Salud Familiar Nuevo Horizonte' },
    { idComuna: 'idQuilaco' , idTipo: 'idCGR' , nombre: 'Consultorio General Rural Quilaco' },
    { idComuna: 'idLosAngeles' , idTipo: 'idPSR' , nombre: 'Posta de Salud Rural Millantú' },
    { idComuna: 'idLosAngeles' , idTipo: 'idPSR' , nombre: 'Posta de Salud Rural Chacayal Norte' },
    { idComuna: 'idLosAngeles' , idTipo: 'idPSR' , nombre: 'Posta de Salud Rural El Durazno ( Los Ángeles)' },
    { idComuna: 'idLosAngeles' , idTipo: 'idPSR' , nombre: 'Posta de Salud Rural Los Molinos' },
    { idComuna: 'idLosAngeles' , idTipo: 'idPSR' , nombre: 'Posta de Salud Rural Llano Blanco' },
    { idComuna: 'idLosAngeles' , idTipo: 'idPSR' , nombre: 'Posta de Salud Rural Los Troncos' },
    { idComuna: 'idLosAngeles' , idTipo: 'idCECOSF' , nombre: 'Centro Comunitario de Salud Familiar El Peral' },
    { idComuna: 'idLosAngeles' , idTipo: 'idPSR' , nombre: 'Posta de Salud Rural San Carlos' },
    { idComuna: 'idLosAngeles' , idTipo: 'idPSR' , nombre: 'Posta de Salud Rural Mesamávida (Los Ángeles)' },
    { idComuna: 'idLosAngeles' , idTipo: 'idPSR' , nombre: 'Posta de Salud Rural San Gerardo' },
    { idComuna: 'idLosAngeles' , idTipo: 'idPSR' , nombre: 'Posta de Salud Rural Dicahue' },
    { idComuna: 'idLosAngeles' , idTipo: 'idPSR' , nombre: 'Posta de Salud Rural Salto del Laja' },
    { idComuna: 'idLosAngeles' , idTipo: 'idPSR' , nombre: 'Posta de Salud Rural Los Robles (Los Ángeles)' },
    { idComuna: 'idLosAngeles' , idTipo: 'idPSR' , nombre: 'Posta de Salud Rural Alborada' },
    { idComuna: 'idAntuco' , idTipo: 'idPSR' , nombre: 'Posta de Salud Rural Los Canelos (Antuco)' },
    { idComuna: 'idMulchen' , idTipo: 'idPSR' , nombre: 'Posta de Salud Rural El Cisne' },
    { idComuna: 'idMulchen' , idTipo: 'idPSR' , nombre: 'Posta de Salud Rural Tierras Libres' },
    { idComuna: 'idMulchen' , idTipo: 'idPSR' , nombre: 'Posta de Salud Rural Santa Adriana' },
    { idComuna: 'idLaja' , idTipo: 'idPSR' , nombre: 'Posta de Salud Rural La Colonia' },
    { idComuna: 'idLaja' , idTipo: 'idPSR' , nombre: 'Posta de Salud Rural Santa Elena (Laja)' },
    { idComuna: 'idLaja' , idTipo: 'idPSR' , nombre: 'Posta de Salud Rural Puente Perales' },
    { idComuna: 'idNacimiento' , idTipo: 'idPSR' , nombre: 'Posta de Salud Rural Dollinco (Nacimiento)' },
    { idComuna: 'idNacimiento' , idTipo: 'idPSR' , nombre: 'Posta de Salud Rural Culenco' },
    { idComuna: 'idNacimiento' , idTipo: 'idPSR' , nombre: 'Posta de Salud Rural Choroico (Nacimiento)' },
    { idComuna: 'idNegrete' , idTipo: 'idPSR' , nombre: 'Posta de Salud Rural Coigue' },
    { idComuna: 'idNacimiento' , idTipo: 'idPSR' , nombre: 'Posta de Salud Rural Millapoa' },
    { idComuna: 'idNacimiento' , idTipo: 'idPSR' , nombre: 'Posta de Salud Rural Carrizal' },
    { idComuna: 'idNacimiento' , idTipo: 'idPSR' , nombre: 'Posta de Salud Rural San Roque' },
    { idComuna: 'idNegrete' , idTipo: 'idPSR' , nombre: 'Posta de Salud Rural Rihue' },
    { idComuna: 'idTucapel' , idTipo: 'idPSR' , nombre: 'Posta de Salud Rural Rucamanqui' },
    { idComuna: 'idQuilaco' , idTipo: 'idPSR' , nombre: 'Posta de Salud Rural Rucalhue' },
    { idComuna: 'idQuilaco' , idTipo: 'idPSR' , nombre: 'Posta de Salud Rural Loncopangue' },
    { idComuna: 'idQuilaco' , idTipo: 'idPSR' , nombre: 'Posta de Salud Rural Campamento' },
    { idComuna: 'idQuilleco' , idTipo: 'idPSR' , nombre: 'Posta de Salud Rural Tinajón' },
    { idComuna: 'idSanRosendo' , idTipo: 'idPSR' , nombre: 'Posta de Salud Rural Turquía' },
    { idComuna: 'idQuilaco' , idTipo: 'idPSR' , nombre: 'Posta de Salud Rural Piñiquihue' },
    { idComuna: 'idAltoBioBio' , idTipo: 'idPSR' , nombre: 'Posta de Salud Rural Pitril' },
    { idComuna: 'idSantaBarbara' , idTipo: 'idPSR' , nombre: 'Posta de Salud Rural Villucura' },
    { idComuna: 'idSantaBarbara' , idTipo: 'idPSR' , nombre: 'Posta de Salud Rural El Huachi' },
    { idComuna: 'idAltoBioBio' , idTipo: 'idPSR' , nombre: 'Posta de Salud Rural Callaqui' },
    { idComuna: 'idAltoBioBio' , idTipo: 'idPSR' , nombre: 'Posta de Salud Rural Trapa Trapa' },
    { idComuna: 'idSantaBarbara' , idTipo: 'idPSR' , nombre: 'Posta de Salud Rural Los Boldos' },
    { idComuna: 'idAltoBioBio' , idTipo: 'idPSR' , nombre: 'Posta de Salud Rural Ralco Lepoy' },
    { idComuna: 'idAltoBioBio' , idTipo: 'idPSR' , nombre: 'Posta de Salud Rural Malla Malla' },
    { idComuna: 'idAltoBioBio' , idTipo: 'idPSR' , nombre: 'Posta de Salud Rural Malla Palmucho' },
    { idComuna: 'idYumbel' , idTipo: 'idPSR' , nombre: 'Posta de Salud Rural La Aguada' },
    { idComuna: 'idYumbel' , idTipo: 'idPSR' , nombre: 'Posta de Salud Rural Rere' },
    { idComuna: 'idYumbel' , idTipo: 'idPSR' , nombre: 'Posta de Salud Rural Tomeco' },
    { idComuna: 'idYumbel' , idTipo: 'idPSR' , nombre: 'Posta de Salud Rural Río Claro' },
    { idComuna: 'idCabrero' , idTipo: 'idPSR' , nombre: 'Posta de Salud Rural Chillancito' },
    { idComuna: 'idCabrero' , idTipo: 'idPSR' , nombre: 'Posta de Salud Rural Charrúa' },
    { idComuna: 'idCabrero' , idTipo: 'idPSR' , nombre: 'Posta de Salud Rural Colicheo' },
    { idComuna: 'idTucapel' , idTipo: 'idCGR' , nombre: 'Consultorio General Rural Tucapel' },
    { idComuna: 'idTucapel' , idTipo: 'idPSR' , nombre: 'Posta de Salud Rural Trupán' },
    { idComuna: 'idTucapel' , idTipo: 'idPSR' , nombre: 'Posta de Salud Rural Polcura' },
    { idComuna: 'idCabrero' , idTipo: 'idPSR' , nombre: 'Posta de Salud Rural Quinel' },
    { idComuna: 'idQuilleco' , idTipo: 'idPSR' , nombre: 'Posta de Salud Rural Río Pardo' },
    { idComuna: 'idQuilleco' , idTipo: 'idPSR' , nombre: 'Posta de Salud Rural Cañicura' },
    { idComuna: 'idAltoBioBio' , idTipo: 'idPSR' , nombre: 'Posta de Salud Rural Cauñicú' },
    { idComuna: 'idMulchen' , idTipo: 'idPSR' , nombre: 'Posta de Salud Rural Mañihual' },
    { idComuna: 'idMulchen' , idTipo: 'idPSR' , nombre: 'Posta de Salud Rural Rapelco' },
    { idComuna: 'idLosAngeles' , idTipo: 'idPSR' , nombre: 'Posta de Salud Rural Chacayal Sur' },
    { idComuna: 'idLosAngeles' , idTipo: 'idPSR' , nombre: 'Posta de Salud Rural Virquenco' },
    { idComuna: 'idSantaBarbara' , idTipo: 'idPSR' , nombre: 'Posta de Salud Rural Los Junquillos' },
    { idComuna: 'idMulchen' , idTipo: 'idPSR' , nombre: 'Posta de Salud Rural Alhuelemu' },
    { idComuna: 'idAltoBioBio' , idTipo: 'idPSR' , nombre: 'Posta de Salud Rural Butalelbum' },
    { idComuna: 'idSantaBarbara' , idTipo: 'idPSR' , nombre: 'Posta de Salud Rural El Castillo' },
    { idComuna: 'idYumbel' , idTipo: 'idPSR' , nombre: 'Posta de Salud Rural Canchillas' },
    { idComuna: 'idLosAngeles' , idTipo: 'idCECOSF' , nombre: 'Centro Comunitario de Salud Familiar Galvarino' },
    { idComuna: 'idMulchen' , idTipo: 'idCECOSF' , nombre: 'Centro Comunitario de Salud Familiar Mulchén' },
    { idComuna: 'idNacimiento' , idTipo: 'idCECOSF' , nombre: 'Centro Comunitario de Salud Familiar Julio Hemmelmann' },
    { idComuna: 'idNacimiento' , idTipo: 'idCECOSF' , nombre: 'Centro Comunitario de Salud Familiar Lautaro' },
    { idComuna: 'idLosAngeles' , idTipo: 'idCECOSF' , nombre: 'Centro Comunitario de Salud Familiar Los Pioneros' },
    { idComuna: 'idLosAngeles' , idTipo: 'idCECOSF' , nombre: 'Centro Comunitario de Salud Familiar Villa Los Ríos' },
    { idComuna: 'idLosAngeles' , idTipo: 'idCECOSF' , nombre: 'Centro Comunitario de Salud Familiar Los Carrera' },
    { idComuna: 'idLosAngeles' , idTipo: 'idCECOSF' , nombre: 'Centro Comunitario de Salud Familiar Las Azaleas' },
    { idComuna: 'idCabrero' , idTipo: 'idSAR' , nombre: 'SAR Cabrero' },
    { idComuna: 'idLosAngeles' , idTipo: 'idSAPU' , nombre: 'SAPU Paillihue' },
    { idComuna: 'idLosAngeles' , idTipo: 'idSAR' , nombre: 'SAR Norte' },
    { idComuna: 'idLebu' , idTipo: 'idDireccionServicioSalud' , nombre: 'Actividades gestionadas por la Dirección del Servicio para apoyo de la Red (S.S de Arauco)' },
    { idComuna: 'idLebu' , idTipo: 'idPRAIS' , nombre: 'PRAIS (S.S Arauco)' },
    { idComuna: 'idLebu' , idTipo: 'idClinicaDentalMovil' , nombre: 'Clínica Dental Móvil Triple. Pat. VP5666 (Lebu)' },
    { idComuna: 'idLebu' , idTipo: 'idClinicaDentalMovil' , nombre: 'Clínica Dental Móvil Simple. Pat. VP5664 (Lebu)' },
    { idComuna: 'idLebu' , idTipo: 'idClinicaDentalMovil' , nombre: 'Clínica Dental Móvil Simple. Pat. DDKB17 (Lebu)' },
    { idComuna: 'idCuranilahue' , idTipo: 'idHospital' , nombre: 'Hospital Provincial Dr. Rafael Avaría (Curanilahue)' },
    { idComuna: 'idLebu' , idTipo: 'idHospital' , nombre: 'Hospital de Lebu' },
    { idComuna: 'idCañete' , idTipo: 'idHospital' , nombre: 'Hospital Intercultural Kallvu Llanka (Cañete)' },
    { idComuna: 'idContulmo' , idTipo: 'idHospital' , nombre: 'Hospital de Contulmo' },
    { idComuna: 'idArauco' , idTipo: 'idHospital' , nombre: 'Hospital San Vicente de Arauco' },
    { idComuna: 'idCuranilahue' , idTipo: 'idLabClinicoDental' , nombre: 'Laboratorio Clínico San Pedro' },
    { idComuna: 'idCañete' , idTipo: 'idLabClinicoDental' , nombre: 'Laboratorio Clínico Bio-Test' },
    { idComuna: 'idCañete' , idTipo: 'idLabClinicoDental' , nombre: 'Laboratorio Clínico San Pedro' },
    { idComuna: 'idLebu' , idTipo: 'idCESFAM' , nombre: 'Centro de Salud Familiar Lebu Norte' },
    { idComuna: 'idTirua' , idTipo: 'idCESFAM' , nombre: 'Centro de Salud Familiar Isabel Jiménez' },
    { idComuna: 'idCuranilahue' , idTipo: 'idCESFAM' , nombre: 'Centro de Salud Familiar Eleuterio Ramírez' },
    { idComuna: 'idLosAlamos' , idTipo: 'idCESFAM' , nombre: 'Centro de Salud Familiar Los Álamos' },
    { idComuna: 'idLosAlamos' , idTipo: 'idPSR' , nombre: 'Posta de Salud Rural Cerro Alto' },
    { idComuna: 'idLebu' , idTipo: 'idPSR' , nombre: 'Posta de Salud Rural Pehuén' },
    { idComuna: 'idLosAlamos' , idTipo: 'idPSR' , nombre: 'Posta de Salud Rural Tres Pinos' },
    { idComuna: 'idLosAlamos' , idTipo: 'idPSR' , nombre: 'Posta de Salud Rural Pangue' },
    { idComuna: 'idArauco' , idTipo: 'idPSR' , nombre: 'Posta de Salud Rural Quiapo' },
    { idComuna: 'idLebu' , idTipo: 'idPSR' , nombre: 'Posta de Salud Rural Isla Mocha' },
    { idComuna: 'idArauco' , idTipo: 'idPSR' , nombre: 'Posta de Salud Rural Ramadillas' },
    { idComuna: 'idArauco' , idTipo: 'idPSR' , nombre: 'Posta de Salud Rural Punta Lavapié' },
    { idComuna: 'idArauco' , idTipo: 'idCESFAM' , nombre: 'Centro de Salud Familiar Laraquete' },
    { idComuna: 'idCañete' , idTipo: 'idPSR' , nombre: 'Posta de Salud Rural Cayucupil' },
    { idComuna: 'idCañete' , idTipo: 'idCECOSF' , nombre: 'Centro Comunitario de Salud Familiar Antiquina' },
    { idComuna: 'idLosAlamos' , idTipo: 'idPSR' , nombre: 'Posta de Salud Rural Antihuala' },
    { idComuna: 'idCañete' , idTipo: 'idPSR' , nombre: 'Posta de Salud Rural Huentelolén' },
    { idComuna: 'idTirua' , idTipo: 'idPSR' , nombre: 'Posta de Salud Rural Quidico' },
    { idComuna: 'idTirua' , idTipo: 'idPSR' , nombre: 'Posta de Salud Rural Ranquilhue' },
    { idComuna: 'idTirua' , idTipo: 'idPSR' , nombre: 'Posta de Salud Rural Alto Quilantahue' },
    { idComuna: 'idTirua' , idTipo: 'idPSR' , nombre: 'Posta de Salud Rural Casa de Piedra' },
    { idComuna: 'idCañete' , idTipo: 'idPSR' , nombre: 'Posta de Salud Rural Llenquehue' },
    { idComuna: 'idCañete' , idTipo: 'idPSR' , nombre: 'Posta de Salud Rural Lloncao' },
    { idComuna: 'idCañete' , idTipo: 'idPSR' , nombre: 'Posta de Salud Rural Pocuno' },
    { idComuna: 'idContulmo' , idTipo: 'idCECOSF' , nombre: 'Centro Comunitario de Salud Familiar Elicura' },
    { idComuna: 'idContulmo' , idTipo: 'idPSR' , nombre: 'Posta de Salud Rural Mahuilque Bajo' },
    { idComuna: 'idContulmo' , idTipo: 'idPSR' , nombre: 'Posta de Salud Rural Los Huapes de Aillahuampi' },
    { idComuna: 'idContulmo' , idTipo: 'idPSR' , nombre: 'Posta de Salud Rural Huillinco' },
    { idComuna: 'idArauco' , idTipo: 'idCESFAM' , nombre: 'Centro de Salud Familiar Carampangue' },
    { idComuna: 'idArauco' , idTipo: 'idPSR' , nombre: 'Posta de Salud Rural Las Puentes' },
    { idComuna: 'idArauco' , idTipo: 'idPSR' , nombre: 'Posta de Salud Rural Yani' },
    { idComuna: 'idCuranilahue' , idTipo: 'idPSR' , nombre: 'Posta de Salud Rural San José de Colico' },
    { idComuna: 'idLebu' , idTipo: 'idPSR' , nombre: 'Posta de Salud Rural Santa Rosa (Lebu)' },
    { idComuna: 'idArauco' , idTipo: 'idPSR' , nombre: 'Posta de Salud Rural Llico (Arauco)' },
    { idComuna: 'idLosAlamos' , idTipo: 'idPSR' , nombre: 'Posta de Salud Rural Ranquilco' },
    { idComuna: 'idCañete' , idTipo: 'idPSR' , nombre: 'Posta de Salud Rural Pangueco (Cañete)' },
    { idComuna: 'idTirua' , idTipo: 'idPSR' , nombre: 'Posta de Salud Rural Primer Agua' },
    { idComuna: 'idTirua' , idTipo: 'idPSR' , nombre: 'Posta de Salud Rural Loncotripai' },
    { idComuna: 'idCuranilahue' , idTipo: 'idCOSAM' , nombre: 'COSAM Curanilahue' },
    { idComuna: 'idLebu' , idTipo: 'idCOSAM' , nombre: 'COSAM Lebu' },
    { idComuna: 'idCañete' , idTipo: 'idCOSAM' , nombre: 'COSAM Cañete' },
    { idComuna: 'idArauco' , idTipo: 'idCOSAM' , nombre: 'COSAM de Arauco' },
    { idComuna: 'idLosAlamos' , idTipo: 'idCECOSF' , nombre: 'Centro Comunitario de Salud Familiar Los Álamos' },
    { idComuna: 'idArauco' , idTipo: 'idCESFAM' , nombre: 'Centro de Salud Familiar Tubul' },
    { idComuna: 'idTirua' , idTipo: 'idCECOSF' , nombre: 'Centro Comunitario de Salud Familiar Quidico' },
    { idComuna: 'idConcepcion' , idTipo: 'idCentroSalud' , nombre: 'Centro Médico Kenal' },
    { idComuna: 'idChiguayante' , idTipo: 'idLabClinicoDental' , nombre: 'Laboratorio Clínico Labomedic' },
    { idComuna: 'idConcepcion' , idTipo: 'idLabClinicoDental' , nombre: 'Laboratorio Clínico MACROLAB' },
    { idComuna: 'idConcepcion' , idTipo: 'idCentroSalud' , nombre: 'Centro Médico Integramédica Bio Bio' },
    { idComuna: 'idLaja' , idTipo: 'idCentroSalud' , nombre: 'Policlínico AChS Laja' },
    { idComuna: 'idCabrero' , idTipo: 'idCentroSalud' , nombre: 'Policlínico AChS Cabrero' },
    { idComuna: 'idArauco' , idTipo: 'idCentroSalud' , nombre: 'Policlínico Asociación Chilena de Seguridad AChS Arauco' },
    { idComuna: 'idCañete' , idTipo: 'idCentroSalud' , nombre: 'Policlínico Asociación Chilena de Seguridad AChS Cañete' },
    { idComuna: 'idConcepcion' , idTipo: 'idCECOSF' , nombre: 'Centro Comunitario de Salud Familiar Chaimávida' },
    { idComuna: 'idLota' , idTipo: 'idSAPU' , nombre: 'SAPU Dr. Juan Cartes Arias' },
    { idComuna: 'idHualpen' , idTipo: 'idSAPU' , nombre: 'SAPU La Floresta' },
    { idComuna: 'idConcepcion' , idTipo: 'idSAR' , nombre: 'SAR Víctor Manuel Fernández' },
    { idComuna: 'idTome' , idTipo: 'idSAPU' , nombre: 'SAPU Bellavista' },
    { idComuna: 'idCuranilahue' , idTipo: 'idSAPU' , nombre: 'SAPU Eleuterio Ramírez' },
    { idComuna: 'idLosAlamos' , idTipo: 'idSAR' , nombre: 'SAR Los Álamos' },
    { idComuna: 'idLosAngeles' , idTipo: 'idSAPU' , nombre: 'SAPU 2 Septiembre' },
    { idComuna: 'idLosAngeles' , idTipo: 'idSAPU' , nombre: 'SAPU Nororiente' },
    { idComuna: 'idLosAngeles' , idTipo: 'idSAPU' , nombre: 'SAPU Nuevo Horizonte' },
    { idComuna: 'idCuranilahue' , idTipo: 'idCentroSalud' , nombre: 'Policlínico ACHS Curanilahue' },
    { idComuna: 'idNacimiento' , idTipo: 'idClinicaDental' , nombre: 'Clínica Dental CMPC Maderas S.A.' },
    { idComuna: 'idCabrero' , idTipo: 'idCECOSF' , nombre: 'Centro Comunitario de Salud Familiar Cabrero' },
    { idComuna: 'idSantaBarbara' , idTipo: 'idCECOSF' , nombre: 'Centro Comunitario de Salud Familiar Santa Bárbara' },
    { idComuna: 'idLaja' , idTipo: 'idCECOSF' , nombre: 'Centro Comunitario de Salud Familiar Laja' },
    { idComuna: 'idHualpen' , idTipo: 'idCECOSF' , nombre: 'Centro Comunitario de Salud Familiar Parque Central' },
    { idComuna: 'idTalcahuano' , idTipo: 'idCECOSF' , nombre: 'Centro Comunitario de Salud Familiar Villa Centinela' },
    { idComuna: 'idPenco' , idTipo: 'idCECOSF' , nombre: 'Centro Comunitario de Salud Familiar Ríos de Chile' },
    { idComuna: 'idTome' , idTipo: 'idCECOSF' , nombre: 'Centro Comunitario de Salud Familiar Punta de Parra' },
    { idComuna: 'idLosAngeles' , idTipo: 'idCESFAM' , nombre: 'Centro de Salud Familiar Entre Ríos' },
    { idComuna: 'idConcepcion' , idTipo: 'idLabClinicoDental' , nombre: 'Laboratorio Clínico Novalab Chile' },
    { idComuna: 'idConcepcion' , idTipo: 'idCRS' , nombre: 'Centro de Referencia de Salud Municipal' },
    { idComuna: 'idHualpen' , idTipo: 'idCentroComunitarioDemencia' , nombre: 'Centro Diurno para Personas con Demencia' },
    { idComuna: 'idSanPedroDeLaPaz' , idTipo: 'idCECOSF' , nombre: 'Centro Comunitario de Salud Familiar Boca Sur Viejo' },
    { idComuna: 'idMulchen' , idTipo: 'idCECOSF' , nombre: 'Centro Comunitario de Salud Familiar Villa La Granja' },
    { idComuna: 'idTome' , idTipo: 'idCECOSF' , nombre: 'Centro Comunitario de Salud Familiar Cerro Estanque' },
]

export default dataEstablecimientos